/*WITH PFL_EXPENSE_RPT_INSERT_DB as 
(

    select * from {{ ref('j_R12_301_PFL_AP_EXPENSE_REPORT_DS_Ld_DS_Pfl_Expense_Report') }}
)
select * from PFL_EXPENSE_RPT_INSERT_DB
*/

{{ config(
    materialized='table', 
    schema='ITSS_AP',    
    alias='PFL_EXPENSE_RPT_INSERT_DB'
) }}

With Oci_Stg_Reject_Exp_Rpt_2Out as (
	Select TABLE_TXN_SEQ_NO, 
		DB_TXN_SEQ_NO, 
		BATCH_ID, 
		REPORT_LINE_ID
 from 
ITSS_AP.STG_REJECT_EXP_RPT
 ),
DS_Pfl_Expense_Report_2Out as(
	select * 
	from  {{ ref('j_R12_301_PFL_AP_EXPENSE_REPORT_DS_Ld_DS_Pfl_Expense_Report') }}
),
Lkp_ColumnOut as (
	Select 
	DS_Pfl_Expense_Report_2Out.REPORT_HEADER_ID as REPORT_HEADER_ID,
	 DS_Pfl_Expense_Report_2Out.REPORT_LINE_ID as REPORT_LINE_ID,
	 DS_Pfl_Expense_Report_2Out.DISTRIBUTION_LINE_NUMBER as DISTRIBUTION_LINE_NUMBER,
	 DS_Pfl_Expense_Report_2Out.AMOUNT as AMOUNT,
	 DS_Pfl_Expense_Report_2Out.CURRENCY_CODE as CURRENCY_CODE,
	 DS_Pfl_Expense_Report_2Out.RECEIPT_CURRENCY_AMOUNT as RECEIPT_CURRENCY_AMOUNT,
	 DS_Pfl_Expense_Report_2Out.DAILY_AMOUNT as DAILY_AMOUNT,
	 DS_Pfl_Expense_Report_2Out.WEB_PARAMETER_ID as WEB_PARAMETER_ID,
	 DS_Pfl_Expense_Report_2Out.CATEGORY_CODE as CATEGORY_CODE,
	 DS_Pfl_Expense_Report_2Out.SUBMITTED_AMOUNT as SUBMITTED_AMOUNT,
	 DS_Pfl_Expense_Report_2Out.ORG_ID as ORG_ID,
	 DS_Pfl_Expense_Report_2Out.ITEMIZATION_PARENT_ID as ITEMIZATION_PARENT_ID,
	 DS_Pfl_Expense_Report_2Out.EMPLOYEE_ID as EMPLOYEE_ID,
	 DS_Pfl_Expense_Report_2Out.PAID_ON_BEHALF_EMPLOYEE_ID as PAID_ON_BEHALF_EMPLOYEE_ID,
	 DS_Pfl_Expense_Report_2Out.WEEK_END_DATE as WEEK_END_DATE,
	 DS_Pfl_Expense_Report_2Out.INVOICE_NUM as INVOICE_NUM,
	 DS_Pfl_Expense_Report_2Out.MAXIMUM_AMOUNT_TO_APPLY as MAXIMUM_AMOUNT_TO_APPLY,
	 DS_Pfl_Expense_Report_2Out.PREPAY_NUM as PREPAY_NUM,
	 DS_Pfl_Expense_Report_2Out.EXP_HEADER_VENDOR_SITE_ID as EXP_HEADER_VENDOR_SITE_ID,
	 DS_Pfl_Expense_Report_2Out.LEDGER_ID as LEDGER_ID,
	 DS_Pfl_Expense_Report_2Out.SOURCE as SOURCE,
	 DS_Pfl_Expense_Report_2Out.EXPENSE_LINE_CO_CODE as EXPENSE_LINE_CO_CODE,
	 DS_Pfl_Expense_Report_2Out.EXPENSE_LINE_COST_CENTRE as EXPENSE_LINE_COST_CENTRE,
	 DS_Pfl_Expense_Report_2Out.EXPENSE_LINE_NOMINAL_ACCOUNT as EXPENSE_LINE_NOMINAL_ACCOUNT,
	 DS_Pfl_Expense_Report_2Out.EXPENSE_LINE_BRANCH_CODE as EXPENSE_LINE_BRANCH_CODE,
	 DS_Pfl_Expense_Report_2Out.EXPENSE_LINE_PRODUCT_CODE as EXPENSE_LINE_PRODUCT_CODE,
	 DS_Pfl_Expense_Report_2Out.CODE_COMBINATION_ID as CODE_COMBINATION_ID,
	 DS_Pfl_Expense_Report_2Out.COMPANY_CODE as COMPANY_CODE,
	 DS_Pfl_Expense_Report_2Out.PERSON_ID as PERSON_ID,
	 DS_Pfl_Expense_Report_2Out.EMPLOYEE_NUMBER as EMPLOYEE_NUMBER,
	 DS_Pfl_Expense_Report_2Out.FULL_NAME as FULL_NAME,
	 DS_Pfl_Expense_Report_2Out.SUPPLIER_VENDOR_SITE_ID as SUPPLIER_VENDOR_SITE_ID,
	 DS_Pfl_Expense_Report_2Out.OFFICE_HOME_FLAG as OFFICE_HOME_FLAG,
	 DS_Pfl_Expense_Report_2Out.DELETION_FLAG as DELETION_FLAG,
	 DS_Pfl_Expense_Report_2Out.EXPENSE_REPORT_S as EXPENSE_REPORT_S,
	 DS_Pfl_Expense_Report_2Out.FILE_ID as FILE_ID,
	 DS_Pfl_Expense_Report_2Out.RECORD_CREATE_DATETIME as RECORD_CREATE_DATETIME,
	 DS_Pfl_Expense_Report_2Out.RECORD_LAST_UPDATE_DATETIME as RECORD_LAST_UPDATE_DATETIME,
	 DS_Pfl_Expense_Report_2Out.BATCH_LOAD_ID as BATCH_LOAD_ID,
	 DS_Pfl_Expense_Report_2Out.SOURCE_SYSTEM_CODE as SOURCE_SYSTEM_CODE,
	 DS_Pfl_Expense_Report_2Out.DB_TXN_SEQ_NUM as DB_TXN_SEQ_NUM,
	 DS_Pfl_Expense_Report_2Out.TABLE_TXN_SEQ_NUM as TABLE_TXN_SEQ_NUM,
	 Oci_Stg_Reject_Exp_Rpt_2Out.REPORT_LINE_ID as REPORT_LINE_ID_1,
	 DS_Pfl_Expense_Report_2Out.REPROCESS_COUNTER as REPROCESS_COUNTER 
FROM
	 DS_Pfl_Expense_Report_2Out as DS_Pfl_Expense_Report_2Out 
 LEFT JOIN Oci_Stg_Reject_Exp_Rpt_2Out as Oci_Stg_Reject_Exp_Rpt_2Out 
ON
	DS_Pfl_Expense_Report_2Out.REPORT_LINE_ID = Oci_Stg_Reject_Exp_Rpt_2Out.REPORT_LINE_ID
),

DSstgVar_Xfm_Columns_2Out2 as (
	Select 
	CASE  WHEN REPORT_LINE_ID_1 IS NULL THEN 0  ELSE 1 END as SvarReject,
	 REPORT_HEADER_ID as REPORT_HEADER_ID,
	 REPORT_LINE_ID as REPORT_LINE_ID,
	 DISTRIBUTION_LINE_NUMBER as DISTRIBUTION_LINE_NUMBER,
	 AMOUNT as AMOUNT,
	 CURRENCY_CODE as CURRENCY_CODE,
	 RECEIPT_CURRENCY_AMOUNT as RECEIPT_CURRENCY_AMOUNT,
	 DAILY_AMOUNT as DAILY_AMOUNT,
	 WEB_PARAMETER_ID as WEB_PARAMETER_ID,
	 CATEGORY_CODE as CATEGORY_CODE,
	 SUBMITTED_AMOUNT as SUBMITTED_AMOUNT,
	 ORG_ID as ORG_ID,
	 ITEMIZATION_PARENT_ID as ITEMIZATION_PARENT_ID,
	 EMPLOYEE_ID as EMPLOYEE_ID,
	 PAID_ON_BEHALF_EMPLOYEE_ID as PAID_ON_BEHALF_EMPLOYEE_ID,
	 WEEK_END_DATE as WEEK_END_DATE,
	 INVOICE_NUM as INVOICE_NUM,
	 MAXIMUM_AMOUNT_TO_APPLY as MAXIMUM_AMOUNT_TO_APPLY,
	 PREPAY_NUM as PREPAY_NUM,
	 EXP_HEADER_VENDOR_SITE_ID as EXP_HEADER_VENDOR_SITE_ID,
	 LEDGER_ID as LEDGER_ID,
	 SOURCE as SOURCE,
	 EXPENSE_LINE_CO_CODE as EXPENSE_LINE_CO_CODE,
	 EXPENSE_LINE_COST_CENTRE as EXPENSE_LINE_COST_CENTRE,
	 EXPENSE_LINE_NOMINAL_ACCOUNT as EXPENSE_LINE_NOMINAL_ACCOUNT,
	 EXPENSE_LINE_BRANCH_CODE as EXPENSE_LINE_BRANCH_CODE,
	 EXPENSE_LINE_PRODUCT_CODE as EXPENSE_LINE_PRODUCT_CODE,
	 CODE_COMBINATION_ID as CODE_COMBINATION_ID,
	 COMPANY_CODE as COMPANY_CODE,
	 PERSON_ID as PERSON_ID,
	 EMPLOYEE_NUMBER as EMPLOYEE_NUMBER,
	 FULL_NAME as FULL_NAME,
	 SUPPLIER_VENDOR_SITE_ID as SUPPLIER_VENDOR_SITE_ID,
	 OFFICE_HOME_FLAG as OFFICE_HOME_FLAG,
	 DELETION_FLAG as DELETION_FLAG,
	 EXPENSE_REPORT_S as EXPENSE_REPORT_S,
	 FILE_ID as FILE_ID,
	 RECORD_CREATE_DATETIME as RECORD_CREATE_DATETIME,
	 RECORD_LAST_UPDATE_DATETIME as RECORD_LAST_UPDATE_DATETIME,
	 BATCH_LOAD_ID as BATCH_LOAD_ID,
	 SOURCE_SYSTEM_CODE as SOURCE_SYSTEM_CODE,
	 DB_TXN_SEQ_NUM as DB_TXN_SEQ_NUM,
	 TABLE_TXN_SEQ_NUM as TABLE_TXN_SEQ_NUM,
	 REPORT_LINE_ID as REPORT_LINE_ID_1,
	 REPROCESS_COUNTER as REPROCESS_COUNTER 
From Lkp_ColumnOut as Lkp_ColumnOut),

DSfilr_Lnk_Xfm_To_PFL_2Out as (
	Select 
	SvarReject,
	 REPORT_HEADER_ID,
	 REPORT_LINE_ID,
	 DISTRIBUTION_LINE_NUMBER,
	 AMOUNT,
	 CURRENCY_CODE,
	 RECEIPT_CURRENCY_AMOUNT,
	 DAILY_AMOUNT,
	 WEB_PARAMETER_ID,
	 CATEGORY_CODE,
	 SUBMITTED_AMOUNT,
	 ORG_ID,
	 ITEMIZATION_PARENT_ID,
	 EMPLOYEE_ID,
	 PAID_ON_BEHALF_EMPLOYEE_ID,
	 WEEK_END_DATE,
	 INVOICE_NUM,
	 MAXIMUM_AMOUNT_TO_APPLY,
	 PREPAY_NUM,
	 EXP_HEADER_VENDOR_SITE_ID,
	 LEDGER_ID,
	 SOURCE,
	 EXPENSE_LINE_CO_CODE,
	 EXPENSE_LINE_COST_CENTRE,
	 EXPENSE_LINE_NOMINAL_ACCOUNT,
	 EXPENSE_LINE_BRANCH_CODE,
	 EXPENSE_LINE_PRODUCT_CODE,
	 CODE_COMBINATION_ID,
	 COMPANY_CODE,
	 PERSON_ID,
	 EMPLOYEE_NUMBER,
	 FULL_NAME,
	 SUPPLIER_VENDOR_SITE_ID,
	 OFFICE_HOME_FLAG,
	 DELETION_FLAG,
	 EXPENSE_REPORT_S,
	 FILE_ID,
	 RECORD_CREATE_DATETIME,
	 RECORD_LAST_UPDATE_DATETIME,
	 BATCH_LOAD_ID,
	 SOURCE_SYSTEM_CODE,
	 DB_TXN_SEQ_NUM,
	 TABLE_TXN_SEQ_NUM,
	 REPORT_LINE_ID_1,
	 REPROCESS_COUNTER 
From DSstgVar_Xfm_Columns_2Out2 as DSstgVar_Xfm_Columns_2Out2 Where SvarReject = 0),

Lnk_Xfm_To_PFL_2Out as (
	Select 
	REPORT_HEADER_ID as REPORT_HEADER_ID,
	 REPORT_LINE_ID as REPORT_LINE_ID,
	 DISTRIBUTION_LINE_NUMBER as DISTRIBUTION_LINE_NUMBER,
	 AMOUNT as AMOUNT,
	 CURRENCY_CODE as CURRENCY_CODE,
	 RECEIPT_CURRENCY_AMOUNT as RECEIPT_CURRENCY_AMOUNT,
	 DAILY_AMOUNT as DAILY_AMOUNT,
	 WEB_PARAMETER_ID as WEB_PARAMETER_ID,
	 CATEGORY_CODE as CATEGORY_CODE,
	 SUBMITTED_AMOUNT as SUBMITTED_AMOUNT,
	 ORG_ID as ORG_ID,
	 ITEMIZATION_PARENT_ID as ITEMIZATION_PARENT_ID,
	 EMPLOYEE_ID as EMPLOYEE_ID,
	 PAID_ON_BEHALF_EMPLOYEE_ID as PAID_ON_BEHALF_EMPLOYEE_ID,
	 WEEK_END_DATE as WEEK_END_DATE,
	 INVOICE_NUM as INVOICE_NUM,
	 MAXIMUM_AMOUNT_TO_APPLY as MAXIMUM_AMOUNT_TO_APPLY,
	 PREPAY_NUM as PREPAY_NUM,
	 EXP_HEADER_VENDOR_SITE_ID as EXP_HEADER_VENDOR_SITE_ID,
	 LEDGER_ID as LEDGER_ID,
	 SOURCE as SOURCE,
	 EXPENSE_LINE_CO_CODE as EXPENSE_LINE_CO_CODE,
	 EXPENSE_LINE_COST_CENTRE as EXPENSE_LINE_COST_CENTRE,
	 EXPENSE_LINE_NOMINAL_ACCOUNT as EXPENSE_LINE_NOMINAL_ACCOUNT,
	 EXPENSE_LINE_BRANCH_CODE as EXPENSE_LINE_BRANCH_CODE,
	 EXPENSE_LINE_PRODUCT_CODE as EXPENSE_LINE_PRODUCT_CODE,
	 CODE_COMBINATION_ID as CODE_COMBINATION_ID,
	 COMPANY_CODE as COMPANY_CODE,
	 PERSON_ID as PERSON_ID,
	 EMPLOYEE_NUMBER as EMPLOYEE_NUMBER,
	 FULL_NAME as FULL_NAME,
	 SUPPLIER_VENDOR_SITE_ID as SUPPLIER_VENDOR_SITE_ID,
	 OFFICE_HOME_FLAG as OFFICE_HOME_FLAG,
	 DELETION_FLAG as DELETION_FLAG,
	 EXPENSE_REPORT_S as EXPENSE_REPORT_S,
	 FILE_ID as FILE_ID,
	 CURRENT_TIMESTAMP as RECORD_CREATE_DATETIME,
	 CURRENT_TIMESTAMP as RECORD_LAST_UPDATE_DATETIME,
	 BATCH_LOAD_ID as BATCH_LOAD_ID,
	 SOURCE_SYSTEM_CODE as SOURCE_SYSTEM_CODE,
	 DB_TXN_SEQ_NUM as DB_TXN_SEQ_NUM,
	 TABLE_TXN_SEQ_NUM as TABLE_TXN_SEQ_NUM 
From DSfilr_Lnk_Xfm_To_PFL_2Out as DSfilr_Lnk_Xfm_To_PFL_2Out)


select 
	REPORT_HEADER_ID
	,REPORT_LINE_ID
	,DISTRIBUTION_LINE_NUMBER
	,AMOUNT
	,CURRENCY_CODE
	,RECEIPT_CURRENCY_AMOUNT
	,DAILY_AMOUNT
	,WEB_PARAMETER_ID
	,CATEGORY_CODE
	,SUBMITTED_AMOUNT
	,ORG_ID
	,ITEMIZATION_PARENT_ID
	,EMPLOYEE_ID
	,PAID_ON_BEHALF_EMPLOYEE_ID
	,WEEK_END_DATE
	,INVOICE_NUM
	,MAXIMUM_AMOUNT_TO_APPLY
	,PREPAY_NUM
	,EXP_HEADER_VENDOR_SITE_ID
	,LEDGER_ID
	,SOURCE
	,EXPENSE_LINE_CO_CODE
	,EXPENSE_LINE_COST_CENTRE
	,EXPENSE_LINE_NOMINAL_ACCOUNT
	,EXPENSE_LINE_BRANCH_CODE
	,EXPENSE_LINE_PRODUCT_CODE
	,CODE_COMBINATION_ID
	,COMPANY_CODE
	,PERSON_ID
	,EMPLOYEE_NUMBER
	,FULL_NAME
	,SUPPLIER_VENDOR_SITE_ID
	,OFFICE_HOME_FLAG
	,DELETION_FLAG
	,EXPENSE_REPORT_S
	,FILE_ID
	,RECORD_CREATE_DATETIME
	,RECORD_LAST_UPDATE_DATETIME
	,BATCH_LOAD_ID
	,SOURCE_SYSTEM_CODE
	,DB_TXN_SEQ_NUM
	,TABLE_TXN_SEQ_NUM
from Lnk_Xfm_To_PFL_2Out